### ISSUE TITLE
should add pip install 'httpx[http2]'

### ISSUE THREAD

**Issue by thefisherman2103** [Moopinger/crlf-detection-script#1]
Hi,
Cool tool.

If you try to run it with Python 3.9 than you'll get error such as 
ImportError: Using http2=True, but the 'h2' package is not installed. Make sure to install httpx using `pip install httpx[http2]`.

pip install 'httpx[http2]' solve it.

Cheers

**Comment by Moopinger** [comment]
Hi @thefisherman2103 

Thanks you for trying it out, and for the info! I have added it to the requirements.txt. And add a note on the readme. 

Thanks again Cheers!
